

///
angular.module("app",     [
        "controllers",

        "com.2fdevs.videogular",
        "com.2fdevs.videogular.plugins.controls",
        "com.2fdevs.videogular.plugins.overlayplay",
        "com.2fdevs.videogular.plugins.buffering",
        "info.vietnamcode.nampnq.videogular.plugins.youtube"
    ]);
///
angular.module('app').controller('DashboardController', [
  '$scope', '$sce', '$log', '$modal', function($scope, $sce, $log, $modal) {
    $scope.currentTime = 0;
    $scope.totalTime = 0;
    $scope.state = null;
    $scope.volume = 1;
    $scope.isCompleted = false;
    $scope.API = null;
    $scope.onPlayerReady = function(API) {
      return $scope.API = API;
    };
    $scope.onCompleteVideo = function() {
      return $scope.isCompleted = true;
    };
    $scope.onUpdateState = function(state) {
      return $scope.state = state;
    };
    $scope.onUpdateTime = function(currentTime, totalTime) {
      $scope.currentTime = currentTime;
      return $scope.totalTime = totalTime;
    };
    $scope.onUpdateVolume = function(newVol) {
      return $scope.volume = newVol;
    };
    $scope.config = {
      autoHide: false,
      autoHideTime: 3000,
      autoPlay: false,
      sources: [
        {
          src: "https://www.youtube.com/watch?v=OCy5461BtTg"
        }
      ],
      tracks: [
        {
          src: "assets/subs/pale-blue-dot.vtt",
          kind: "subtitles",
          srclang: "en",
          label: "English",
          "default": ""
        }
      ],
      loop: false,
      preload: "auto",
      transclude: true,
      controls: void 0,
      theme: {
        url: "bower_components/videogular-themes-default/videogular.css"
      },
      plugins: {
        poster: {
          url: "http://www.videogular.com/assets/images/videogular.png"
        }
      }
    };
    $scope.$watch(function() {
      return $scope.user;
    }, function(nv, ov) {
      if ((nv.id_user != null)) {
        $log.debug(nv);
        if ($scope.isOpenInitial === false) {
          if (parseInt($scope.user.ss_flag_personal_info_user, 10) + parseInt($scope.user.ss_flag_address_info_user, 10) + parseInt($scope.user.ss_flag_services_info_user, 10) + parseInt($scope.user.ss_flag_time_available_info_user, 10) < 4) {
            return $scope.open();
          }
        }
      }
    }, true);
    $scope.isOpenInitial = false;
    return $scope.open = function() {
      var modalInstance;
      $scope.isOpenInitial = true;
      modalInstance = $modal.open({
        templateUrl: 'initial_modal.html',
        controller: 'InitialModalController',
        size: 'lg',
        animate: false,
        resolve: {
          'happening': function() {
            return {
              user: $scope.user
            };
          }
        },
        backdrop: false,
        backdropClass: 'backdrop-item'
      });
      return modalInstance.result.then(function(result) {}, function(e) {});
    };
  }
]);

// ---
// generated by coffee-script 1.9.2